# 赞助本项目

# 这些平台支持对本项目的赞助：

github: [zsbai780518]
patreon: # 替换 Patreon 用户名
open_collective: # 替换 Open Collective 名称
ko_fi: # 替换 Ko-fi 用户名
tidelift: # 替换 Tidelift 包名称
community_bridge: # 替换 Community Bridge 项目名称
liberapay: # 替换 Liberapay 用户名
issuehunt: # 替换 IssueHunt 用户名
otechie: # 替换 Otechie 用户名
lfx_crowdfunding: # 替换 LFX Crowdfunding 项目名称

# 自定义赞助方式：
custom: ['https://github.com/zsbai780518/ai-copyright-saas/blob/main/docs/SPONSOR.md']
